[2024-03-01 11:19:34,420] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:19:34,425] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:19:34,425] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:34,425] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:34,425] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:34,441] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-17 00:00:00+00:00
[2024-03-01 11:19:34,443] {standard_task_runner.py:52} INFO - Started process 20057 to run task
[2024-03-01 11:19:34,445] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-17T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpj0terb3u', '--error-file', '/tmp/tmp4w_4kqsr']
[2024-03-01 11:19:34,446] {standard_task_runner.py:80} INFO - Job 20: Subtask cria_pasta
[2024-03-01 11:19:34,476] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:34,498] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:34,502] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221017T000000, start_date=20240301T141934, end_date=20240301T141934
[2024-03-01 11:19:34,514] {standard_task_runner.py:92} ERROR - Failed to execute job 20 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 20057)
[2024-03-01 11:19:34,538] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:34,563] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:22:25,557] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:22:25,563] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:22:25,563] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:25,563] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:25,563] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:25,579] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-17 00:00:00+00:00
[2024-03-01 11:22:25,583] {standard_task_runner.py:52} INFO - Started process 21642 to run task
[2024-03-01 11:22:25,585] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-17T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp1hp6oobe', '--error-file', '/tmp/tmp_6t0lpvz']
[2024-03-01 11:22:25,585] {standard_task_runner.py:80} INFO - Job 27: Subtask cria_pasta
[2024-03-01 11:22:25,615] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:25,657] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-17T00:00:00+00:00
[2024-03-01 11:22:25,658] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:22:25,659] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-24"']
[2024-03-01 11:22:25,664] {subprocess.py:85} INFO - Output:
[2024-03-01 11:22:25,665] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:22:25,683] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221017T000000, start_date=20240301T142225, end_date=20240301T142225
[2024-03-01 11:22:25,719] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:22:25,742] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:28,340] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:28:28,347] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:28:28,347] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:28,348] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:28,348] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:28,363] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-17 00:00:00+00:00
[2024-03-01 11:28:28,367] {standard_task_runner.py:52} INFO - Started process 23453 to run task
[2024-03-01 11:28:28,369] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-17T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmppr2b224e', '--error-file', '/tmp/tmpr2n4tinu']
[2024-03-01 11:28:28,369] {standard_task_runner.py:80} INFO - Job 27: Subtask cria_pasta
[2024-03-01 11:28:28,401] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:28,444] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-17T00:00:00+00:00
[2024-03-01 11:28:28,445] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:28:28,445] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-24"']
[2024-03-01 11:28:28,451] {subprocess.py:85} INFO - Output:
[2024-03-01 11:28:28,452] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:28:28,471] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221017T000000, start_date=20240301T142828, end_date=20240301T142828
[2024-03-01 11:28:28,504] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:28,525] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:07,818] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:30:07,825] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:30:07,825] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:07,825] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:07,825] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:07,841] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-17 00:00:00+00:00
[2024-03-01 11:30:07,844] {standard_task_runner.py:52} INFO - Started process 24209 to run task
[2024-03-01 11:30:07,846] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-17T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp1_wd_l4y', '--error-file', '/tmp/tmpfo17nuc_']
[2024-03-01 11:30:07,847] {standard_task_runner.py:80} INFO - Job 27: Subtask cria_pasta
[2024-03-01 11:30:07,882] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-17T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:07,929] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-17T00:00:00+00:00
[2024-03-01 11:30:07,929] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:30:07,930] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-24"']
[2024-03-01 11:30:07,937] {subprocess.py:85} INFO - Output:
[2024-03-01 11:30:07,940] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:30:07,959] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221017T000000, start_date=20240301T143007, end_date=20240301T143007
[2024-03-01 11:30:07,980] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:08,004] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
