[2024-03-01 11:19:21,761] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:19:21,765] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:19:21,766] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:21,766] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:21,766] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:21,780] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2024-03-01 11:19:21,783] {standard_task_runner.py:52} INFO - Started process 19931 to run task
[2024-03-01 11:19:21,786] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp7y286bo9', '--error-file', '/tmp/tmpa5qr2349']
[2024-03-01 11:19:21,786] {standard_task_runner.py:80} INFO - Job 14: Subtask cria_pasta
[2024-03-01 11:19:21,819] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:21,844] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:21,847] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20240301T141921, end_date=20240301T141921
[2024-03-01 11:19:21,859] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 19931)
[2024-03-01 11:19:21,879] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:21,902] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:21:57,956] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:21:57,963] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:21:57,963] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:21:57,963] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:21:57,963] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:21:57,979] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2024-03-01 11:21:57,982] {standard_task_runner.py:52} INFO - Started process 21389 to run task
[2024-03-01 11:21:57,985] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpsw979us4', '--error-file', '/tmp/tmphkhyfkhn']
[2024-03-01 11:21:57,985] {standard_task_runner.py:80} INFO - Job 15: Subtask cria_pasta
[2024-03-01 11:21:58,015] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:21:58,065] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2024-03-01 11:21:58,067] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:21:58,067] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-12"']
[2024-03-01 11:21:58,074] {subprocess.py:85} INFO - Output:
[2024-03-01 11:21:58,077] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:21:58,099] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20240301T142157, end_date=20240301T142158
[2024-03-01 11:21:58,118] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:21:58,143] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:01,414] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:28:01,421] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:28:01,421] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:01,421] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:01,421] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:01,561] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2024-03-01 11:28:01,564] {standard_task_runner.py:52} INFO - Started process 23206 to run task
[2024-03-01 11:28:01,566] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmptt98ewbc', '--error-file', '/tmp/tmp383555d5']
[2024-03-01 11:28:01,567] {standard_task_runner.py:80} INFO - Job 15: Subtask cria_pasta
[2024-03-01 11:28:01,598] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:01,647] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2024-03-01 11:28:01,648] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:28:01,648] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-12"']
[2024-03-01 11:28:01,654] {subprocess.py:85} INFO - Output:
[2024-03-01 11:28:01,655] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:28:01,778] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20240301T142801, end_date=20240301T142801
[2024-03-01 11:28:01,821] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:01,844] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:40,604] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:29:40,609] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:29:40,610] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:40,610] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:40,610] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:40,626] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-05 00:00:00+00:00
[2024-03-01 11:29:40,630] {standard_task_runner.py:52} INFO - Started process 23957 to run task
[2024-03-01 11:29:40,632] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpiyp5086n', '--error-file', '/tmp/tmp0nfi81ey']
[2024-03-01 11:29:40,632] {standard_task_runner.py:80} INFO - Job 15: Subtask cria_pasta
[2024-03-01 11:29:40,670] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-05T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:40,720] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2024-03-01 11:29:40,721] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:29:40,722] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-12"']
[2024-03-01 11:29:40,727] {subprocess.py:85} INFO - Output:
[2024-03-01 11:29:40,729] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:29:40,750] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220905T000000, start_date=20240301T142940, end_date=20240301T142940
[2024-03-01 11:29:40,806] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:40,830] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
