[2024-03-01 11:22:31,048] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:22:31,054] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:22:31,054] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:31,054] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:31,054] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:31,070] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-17 00:00:00+00:00
[2024-03-01 11:22:31,073] {standard_task_runner.py:52} INFO - Started process 21702 to run task
[2024-03-01 11:22:31,075] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-17T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpxn7tessp', '--error-file', '/tmp/tmp1xasiv29']
[2024-03-01 11:22:31,075] {standard_task_runner.py:80} INFO - Job 30: Subtask extrai_dados
[2024-03-01 11:22:31,106] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:31,148] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-17T00:00:00+00:00
[2024-03-01 11:22:33,281] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 33, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-10-24'
[2024-03-01 11:22:33,286] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221017T000000, start_date=20240301T142231, end_date=20240301T142233
[2024-03-01 11:22:33,299] {standard_task_runner.py:92} ERROR - Failed to execute job 30 for task extrai_dados (Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-10-24'; 21702)
[2024-03-01 11:22:33,306] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:22:33,318] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:32,288] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:28:32,294] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:28:32,294] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:32,294] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:32,295] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:32,311] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-17 00:00:00+00:00
[2024-03-01 11:28:32,314] {standard_task_runner.py:52} INFO - Started process 23493 to run task
[2024-03-01 11:28:32,317] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-17T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpvsew268l', '--error-file', '/tmp/tmpcyrwid9p']
[2024-03-01 11:28:32,317] {standard_task_runner.py:80} INFO - Job 29: Subtask extrai_dados
[2024-03-01 11:28:32,349] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:32,393] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-17T00:00:00+00:00
[2024-03-01 11:28:33,047] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:28:33,051] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221017T000000, start_date=20240301T142832, end_date=20240301T142833
[2024-03-01 11:28:33,095] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:33,107] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:12,398] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:30:12,408] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [queued]>
[2024-03-01 11:30:12,408] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:12,408] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:12,408] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:12,424] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-17 00:00:00+00:00
[2024-03-01 11:30:12,430] {standard_task_runner.py:52} INFO - Started process 24249 to run task
[2024-03-01 11:30:12,434] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-17T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpgwsgpn6b', '--error-file', '/tmp/tmpjuvwya61']
[2024-03-01 11:30:12,435] {standard_task_runner.py:80} INFO - Job 29: Subtask extrai_dados
[2024-03-01 11:30:12,473] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-17T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:12,528] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-17T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-17T00:00:00+00:00
[2024-03-01 11:30:13,280] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:30:13,286] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221017T000000, start_date=20240301T143012, end_date=20240301T143013
[2024-03-01 11:30:13,331] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:13,347] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
