[2024-03-01 11:22:27,091] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2024-03-01 11:22:27,097] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2024-03-01 11:22:27,097] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:27,097] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:27,097] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:27,111] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-10 00:00:00+00:00
[2024-03-01 11:22:27,114] {standard_task_runner.py:52} INFO - Started process 21662 to run task
[2024-03-01 11:22:27,117] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpo3wzgntl', '--error-file', '/tmp/tmpexbqi752']
[2024-03-01 11:22:27,117] {standard_task_runner.py:80} INFO - Job 28: Subtask extrai_dados
[2024-03-01 11:22:27,147] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-10T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:27,188] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-10T00:00:00+00:00
[2024-03-01 11:22:27,948] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 33, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-10-17'
[2024-03-01 11:22:27,952] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221010T000000, start_date=20240301T142227, end_date=20240301T142227
[2024-03-01 11:22:27,966] {standard_task_runner.py:92} ERROR - Failed to execute job 28 for task extrai_dados (Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-10-17'; 21662)
[2024-03-01 11:22:27,977] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:22:27,989] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:29,875] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2024-03-01 11:28:29,881] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2024-03-01 11:28:29,881] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:29,881] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:29,881] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:29,896] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-10 00:00:00+00:00
[2024-03-01 11:28:29,899] {standard_task_runner.py:52} INFO - Started process 23473 to run task
[2024-03-01 11:28:29,901] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp9yxac2iy', '--error-file', '/tmp/tmprbur2xtl']
[2024-03-01 11:28:29,901] {standard_task_runner.py:80} INFO - Job 28: Subtask extrai_dados
[2024-03-01 11:28:29,932] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-10T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:29,978] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-10T00:00:00+00:00
[2024-03-01 11:28:30,695] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:28:30,700] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221010T000000, start_date=20240301T142829, end_date=20240301T142830
[2024-03-01 11:28:30,720] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:30,731] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:09,535] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2024-03-01 11:30:09,543] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-10T00:00:00+00:00 [queued]>
[2024-03-01 11:30:09,543] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:09,543] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:09,543] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:09,560] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-10 00:00:00+00:00
[2024-03-01 11:30:09,564] {standard_task_runner.py:52} INFO - Started process 24229 to run task
[2024-03-01 11:30:09,566] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-10T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpoqxqfidc', '--error-file', '/tmp/tmpqwh_itlj']
[2024-03-01 11:30:09,567] {standard_task_runner.py:80} INFO - Job 28: Subtask extrai_dados
[2024-03-01 11:30:09,610] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-10T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:09,680] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-10T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-10T00:00:00+00:00
[2024-03-01 11:30:10,479] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:30:10,484] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221010T000000, start_date=20240301T143009, end_date=20240301T143010
[2024-03-01 11:30:10,505] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:10,516] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
