[2024-03-01 11:22:09,140] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:22:09,151] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:22:09,151] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:09,151] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:09,151] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:09,167] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-12 00:00:00+00:00
[2024-03-01 11:22:09,170] {standard_task_runner.py:52} INFO - Started process 21492 to run task
[2024-03-01 11:22:09,173] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpau4opvsm', '--error-file', '/tmp/tmp1ye63b2w']
[2024-03-01 11:22:09,173] {standard_task_runner.py:80} INFO - Job 20: Subtask extrai_dados
[2024-03-01 11:22:09,204] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-12T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:09,249] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2024-03-01 11:22:10,056] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 33, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-09-19'
[2024-03-01 11:22:10,062] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220912T000000, start_date=20240301T142209, end_date=20240301T142210
[2024-03-01 11:22:10,074] {standard_task_runner.py:92} ERROR - Failed to execute job 20 for task extrai_dados (Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-09-19'; 21492)
[2024-03-01 11:22:10,112] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:22:10,127] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:12,646] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:28:12,652] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:28:12,652] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:12,652] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:12,652] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:12,668] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-12 00:00:00+00:00
[2024-03-01 11:28:12,671] {standard_task_runner.py:52} INFO - Started process 23311 to run task
[2024-03-01 11:28:12,673] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpmwaeqnp4', '--error-file', '/tmp/tmplgsogymu']
[2024-03-01 11:28:12,673] {standard_task_runner.py:80} INFO - Job 20: Subtask extrai_dados
[2024-03-01 11:28:12,706] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-12T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:12,750] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2024-03-01 11:28:13,427] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:28:13,432] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220912T000000, start_date=20240301T142812, end_date=20240301T142813
[2024-03-01 11:28:13,491] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:13,504] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:51,420] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:29:51,426] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:29:51,426] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:51,426] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:51,426] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:51,441] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-12 00:00:00+00:00
[2024-03-01 11:29:51,444] {standard_task_runner.py:52} INFO - Started process 24061 to run task
[2024-03-01 11:29:51,447] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpkxq11laf', '--error-file', '/tmp/tmpxul8tv57']
[2024-03-01 11:29:51,447] {standard_task_runner.py:80} INFO - Job 20: Subtask extrai_dados
[2024-03-01 11:29:51,493] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-12T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:51,536] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2024-03-01 11:29:52,187] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:29:52,192] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220912T000000, start_date=20240301T142951, end_date=20240301T142952
[2024-03-01 11:29:52,226] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:52,239] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
