[2024-03-01 11:19:23,435] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:19:23,441] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:19:23,441] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:23,441] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:23,441] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:23,455] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2024-03-01 11:19:23,458] {standard_task_runner.py:52} INFO - Started process 19951 to run task
[2024-03-01 11:19:23,461] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp00qpju25', '--error-file', '/tmp/tmp8rqsrm7d']
[2024-03-01 11:19:23,461] {standard_task_runner.py:80} INFO - Job 15: Subtask cria_pasta
[2024-03-01 11:19:23,491] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:23,518] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:23,522] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20240301T141923, end_date=20240301T141923
[2024-03-01 11:19:23,535] {standard_task_runner.py:92} ERROR - Failed to execute job 15 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 19951)
[2024-03-01 11:19:23,554] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:23,579] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:22:05,772] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:22:05,781] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:22:05,781] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:05,781] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:05,781] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:05,797] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2024-03-01 11:22:05,800] {standard_task_runner.py:52} INFO - Started process 21451 to run task
[2024-03-01 11:22:05,802] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmppbhjcejw', '--error-file', '/tmp/tmp2h9ciere']
[2024-03-01 11:22:05,802] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2024-03-01 11:22:05,837] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:05,882] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2024-03-01 11:22:05,883] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:22:05,884] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-19"']
[2024-03-01 11:22:05,890] {subprocess.py:85} INFO - Output:
[2024-03-01 11:22:05,891] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:22:05,912] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20240301T142205, end_date=20240301T142205
[2024-03-01 11:22:05,936] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:22:05,959] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:09,387] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:28:09,394] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:28:09,394] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:09,394] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:09,394] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:09,409] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2024-03-01 11:28:09,413] {standard_task_runner.py:52} INFO - Started process 23270 to run task
[2024-03-01 11:28:09,416] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpnj8phn_w', '--error-file', '/tmp/tmpjbdq2sri']
[2024-03-01 11:28:09,416] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2024-03-01 11:28:09,446] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:09,489] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2024-03-01 11:28:09,490] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:28:09,490] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-19"']
[2024-03-01 11:28:09,496] {subprocess.py:85} INFO - Output:
[2024-03-01 11:28:09,497] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:28:09,516] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20240301T142809, end_date=20240301T142809
[2024-03-01 11:28:09,549] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:09,576] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:48,202] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:29:48,208] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [queued]>
[2024-03-01 11:29:48,208] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:48,208] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:48,208] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:48,224] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-12 00:00:00+00:00
[2024-03-01 11:29:48,228] {standard_task_runner.py:52} INFO - Started process 24020 to run task
[2024-03-01 11:29:48,230] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-12T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp8y9vca_v', '--error-file', '/tmp/tmp06uu_6ew']
[2024-03-01 11:29:48,231] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2024-03-01 11:29:48,266] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-12T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:48,310] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-12T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-12T00:00:00+00:00
[2024-03-01 11:29:48,311] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:29:48,311] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-19"']
[2024-03-01 11:29:48,317] {subprocess.py:85} INFO - Output:
[2024-03-01 11:29:48,319] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:29:48,338] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220912T000000, start_date=20240301T142948, end_date=20240301T142948
[2024-03-01 11:29:48,363] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:48,385] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
