[2024-03-01 11:19:36,614] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:19:36,619] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:19:36,619] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:36,619] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:36,619] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:36,636] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-24 00:00:00+00:00
[2024-03-01 11:19:36,639] {standard_task_runner.py:52} INFO - Started process 20078 to run task
[2024-03-01 11:19:36,641] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp18drcgi0', '--error-file', '/tmp/tmpfcs022j2']
[2024-03-01 11:19:36,641] {standard_task_runner.py:80} INFO - Job 21: Subtask cria_pasta
[2024-03-01 11:19:36,672] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:36,695] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:36,698] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221024T000000, start_date=20240301T141936, end_date=20240301T141936
[2024-03-01 11:19:36,710] {standard_task_runner.py:92} ERROR - Failed to execute job 21 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 20078)
[2024-03-01 11:19:36,734] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:36,759] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:22:29,493] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:22:29,499] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:22:29,499] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:29,499] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:29,499] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:29,513] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-24 00:00:00+00:00
[2024-03-01 11:22:29,517] {standard_task_runner.py:52} INFO - Started process 21682 to run task
[2024-03-01 11:22:29,519] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmptt5tkn4b', '--error-file', '/tmp/tmpdyre_wgg']
[2024-03-01 11:22:29,519] {standard_task_runner.py:80} INFO - Job 29: Subtask cria_pasta
[2024-03-01 11:22:29,547] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:29,587] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-24T00:00:00+00:00
[2024-03-01 11:22:29,588] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:22:29,588] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-31"']
[2024-03-01 11:22:29,594] {subprocess.py:85} INFO - Output:
[2024-03-01 11:22:29,596] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:22:29,614] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221024T000000, start_date=20240301T142229, end_date=20240301T142229
[2024-03-01 11:22:29,652] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:22:29,675] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:35,753] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:28:35,759] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:28:35,759] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:35,759] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:35,759] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:35,774] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-24 00:00:00+00:00
[2024-03-01 11:28:35,778] {standard_task_runner.py:52} INFO - Started process 23520 to run task
[2024-03-01 11:28:35,780] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpt8sd28s3', '--error-file', '/tmp/tmphp99v4q2']
[2024-03-01 11:28:35,781] {standard_task_runner.py:80} INFO - Job 30: Subtask cria_pasta
[2024-03-01 11:28:35,811] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:35,856] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-24T00:00:00+00:00
[2024-03-01 11:28:35,857] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:28:35,857] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-31"']
[2024-03-01 11:28:35,863] {subprocess.py:85} INFO - Output:
[2024-03-01 11:28:35,864] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:28:35,881] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221024T000000, start_date=20240301T142835, end_date=20240301T142835
[2024-03-01 11:28:35,913] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:35,936] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:16,525] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:30:16,530] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:30:16,530] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:16,530] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:16,530] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:16,547] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-24 00:00:00+00:00
[2024-03-01 11:30:16,550] {standard_task_runner.py:52} INFO - Started process 24276 to run task
[2024-03-01 11:30:16,552] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpr8t_k7ez', '--error-file', '/tmp/tmpjaktlcn1']
[2024-03-01 11:30:16,553] {standard_task_runner.py:80} INFO - Job 30: Subtask cria_pasta
[2024-03-01 11:30:16,640] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-24T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:16,718] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-24T00:00:00+00:00
[2024-03-01 11:30:16,719] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:30:16,720] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-31"']
[2024-03-01 11:30:16,727] {subprocess.py:85} INFO - Output:
[2024-03-01 11:30:16,729] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:30:16,749] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221024T000000, start_date=20240301T143016, end_date=20240301T143016
[2024-03-01 11:30:16,767] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:16,790] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
