[2024-03-01 11:19:26,244] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:19:26,249] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:19:26,249] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:26,249] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:26,249] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:26,263] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2024-03-01 11:19:26,267] {standard_task_runner.py:52} INFO - Started process 19974 to run task
[2024-03-01 11:19:26,269] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmppqssjop7', '--error-file', '/tmp/tmpic2yhefe']
[2024-03-01 11:19:26,269] {standard_task_runner.py:80} INFO - Job 16: Subtask cria_pasta
[2024-03-01 11:19:26,300] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:26,324] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:26,328] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20240301T141926, end_date=20240301T141926
[2024-03-01 11:19:26,339] {standard_task_runner.py:92} ERROR - Failed to execute job 16 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 19974)
[2024-03-01 11:19:26,362] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:26,388] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:22:07,567] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:22:07,572] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:22:07,572] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:07,572] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:07,572] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:07,587] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2024-03-01 11:22:07,591] {standard_task_runner.py:52} INFO - Started process 21472 to run task
[2024-03-01 11:22:07,593] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpsg8jeik8', '--error-file', '/tmp/tmpq2w27aie']
[2024-03-01 11:22:07,593] {standard_task_runner.py:80} INFO - Job 19: Subtask cria_pasta
[2024-03-01 11:22:07,630] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:07,673] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2024-03-01 11:22:07,674] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:22:07,675] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-26"']
[2024-03-01 11:22:07,681] {subprocess.py:85} INFO - Output:
[2024-03-01 11:22:07,682] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:22:07,701] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20240301T142207, end_date=20240301T142207
[2024-03-01 11:22:07,726] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:22:07,747] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:11,124] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:28:11,130] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:28:11,130] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:11,130] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:11,130] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:11,146] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2024-03-01 11:28:11,148] {standard_task_runner.py:52} INFO - Started process 23291 to run task
[2024-03-01 11:28:11,151] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpr0rf8shi', '--error-file', '/tmp/tmps3tv_2wk']
[2024-03-01 11:28:11,151] {standard_task_runner.py:80} INFO - Job 19: Subtask cria_pasta
[2024-03-01 11:28:11,180] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:11,229] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2024-03-01 11:28:11,229] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:28:11,230] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-26"']
[2024-03-01 11:28:11,235] {subprocess.py:85} INFO - Output:
[2024-03-01 11:28:11,237] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:28:11,255] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20240301T142811, end_date=20240301T142811
[2024-03-01 11:28:11,284] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:11,304] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:49,887] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:29:49,893] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:29:49,893] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:49,893] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:49,893] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:49,910] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-19 00:00:00+00:00
[2024-03-01 11:29:49,914] {standard_task_runner.py:52} INFO - Started process 24041 to run task
[2024-03-01 11:29:49,916] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp18sul39d', '--error-file', '/tmp/tmpt9_9mpae']
[2024-03-01 11:29:49,917] {standard_task_runner.py:80} INFO - Job 19: Subtask cria_pasta
[2024-03-01 11:29:49,947] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-19T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:49,992] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2024-03-01 11:29:49,993] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:29:49,993] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-26"']
[2024-03-01 11:29:49,999] {subprocess.py:85} INFO - Output:
[2024-03-01 11:29:50,000] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:29:50,019] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220919T000000, start_date=20240301T142949, end_date=20240301T142950
[2024-03-01 11:29:50,050] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:50,075] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
