[2024-03-01 11:19:38,370] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:19:38,376] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:19:38,376] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:38,376] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:38,376] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:38,391] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-31 00:00:00+00:00
[2024-03-01 11:19:38,394] {standard_task_runner.py:52} INFO - Started process 20098 to run task
[2024-03-01 11:19:38,397] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-31T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpx742k42i', '--error-file', '/tmp/tmpiepr39m4']
[2024-03-01 11:19:38,397] {standard_task_runner.py:80} INFO - Job 22: Subtask cria_pasta
[2024-03-01 11:19:38,430] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:38,453] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:38,456] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221031T000000, start_date=20240301T141938, end_date=20240301T141938
[2024-03-01 11:19:38,468] {standard_task_runner.py:92} ERROR - Failed to execute job 22 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 20098)
[2024-03-01 11:19:38,490] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:38,516] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:22:38,434] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:22:38,440] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:22:38,440] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:38,441] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:38,441] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:38,456] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-31 00:00:00+00:00
[2024-03-01 11:22:38,460] {standard_task_runner.py:52} INFO - Started process 21749 to run task
[2024-03-01 11:22:38,462] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-31T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpi5u6f8o3', '--error-file', '/tmp/tmpuxbgeol7']
[2024-03-01 11:22:38,462] {standard_task_runner.py:80} INFO - Job 32: Subtask cria_pasta
[2024-03-01 11:22:38,491] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:38,536] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T00:00:00+00:00
[2024-03-01 11:22:38,537] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:22:38,537] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-11-07"']
[2024-03-01 11:22:38,542] {subprocess.py:85} INFO - Output:
[2024-03-01 11:22:38,544] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:22:38,565] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221031T000000, start_date=20240301T142238, end_date=20240301T142238
[2024-03-01 11:22:38,595] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:22:38,619] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:37,579] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:28:37,585] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:28:37,585] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:37,585] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:37,585] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:37,600] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-31 00:00:00+00:00
[2024-03-01 11:28:37,604] {standard_task_runner.py:52} INFO - Started process 23541 to run task
[2024-03-01 11:28:37,606] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-31T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp3jvqk3k5', '--error-file', '/tmp/tmpl1kzzd58']
[2024-03-01 11:28:37,606] {standard_task_runner.py:80} INFO - Job 31: Subtask cria_pasta
[2024-03-01 11:28:37,638] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:37,681] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T00:00:00+00:00
[2024-03-01 11:28:37,681] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:28:37,682] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-11-07"']
[2024-03-01 11:28:37,688] {subprocess.py:85} INFO - Output:
[2024-03-01 11:28:37,689] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:28:37,707] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221031T000000, start_date=20240301T142837, end_date=20240301T142837
[2024-03-01 11:28:37,739] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:37,762] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:18,416] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:30:18,424] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:30:18,425] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:18,425] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:18,425] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:18,439] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-31 00:00:00+00:00
[2024-03-01 11:30:18,443] {standard_task_runner.py:52} INFO - Started process 24297 to run task
[2024-03-01 11:30:18,445] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-31T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp2fys_k9s', '--error-file', '/tmp/tmpa_3kwdue']
[2024-03-01 11:30:18,445] {standard_task_runner.py:80} INFO - Job 31: Subtask cria_pasta
[2024-03-01 11:30:18,479] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-31T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:18,524] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T00:00:00+00:00
[2024-03-01 11:30:18,525] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:30:18,526] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-11-07"']
[2024-03-01 11:30:18,531] {subprocess.py:85} INFO - Output:
[2024-03-01 11:30:18,533] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:30:18,552] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221031T000000, start_date=20240301T143018, end_date=20240301T143018
[2024-03-01 11:30:18,578] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:18,600] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
