[2024-03-01 11:22:13,237] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:22:13,242] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:22:13,242] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:13,242] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:13,242] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:13,257] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-19 00:00:00+00:00
[2024-03-01 11:22:13,261] {standard_task_runner.py:52} INFO - Started process 21532 to run task
[2024-03-01 11:22:13,263] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp8rwewrkf', '--error-file', '/tmp/tmp_eklr4_8']
[2024-03-01 11:22:13,264] {standard_task_runner.py:80} INFO - Job 22: Subtask extrai_dados
[2024-03-01 11:22:13,294] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:13,337] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2024-03-01 11:22:14,067] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 33, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-09-26'
[2024-03-01 11:22:14,072] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220919T000000, start_date=20240301T142213, end_date=20240301T142214
[2024-03-01 11:22:14,086] {standard_task_runner.py:92} ERROR - Failed to execute job 22 for task extrai_dados (Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-09-26'; 21532)
[2024-03-01 11:22:14,123] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:22:14,137] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:16,616] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:28:16,622] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:28:16,623] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:16,623] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:16,623] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:16,637] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-19 00:00:00+00:00
[2024-03-01 11:28:16,640] {standard_task_runner.py:52} INFO - Started process 23351 to run task
[2024-03-01 11:28:16,642] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpf1hjlk10', '--error-file', '/tmp/tmp1u8kvidq']
[2024-03-01 11:28:16,643] {standard_task_runner.py:80} INFO - Job 22: Subtask extrai_dados
[2024-03-01 11:28:16,672] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:16,717] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2024-03-01 11:28:17,455] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:28:17,459] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220919T000000, start_date=20240301T142816, end_date=20240301T142817
[2024-03-01 11:28:17,502] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:17,514] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:55,307] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:29:55,313] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [queued]>
[2024-03-01 11:29:55,313] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:55,313] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:55,313] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:55,331] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-19 00:00:00+00:00
[2024-03-01 11:29:55,335] {standard_task_runner.py:52} INFO - Started process 24101 to run task
[2024-03-01 11:29:55,337] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-19T00:00:00+00:00', '--job-id', '22', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp0yi057pz', '--error-file', '/tmp/tmprx0sjrp0']
[2024-03-01 11:29:55,338] {standard_task_runner.py:80} INFO - Job 22: Subtask extrai_dados
[2024-03-01 11:29:55,369] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-19T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:55,412] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-19T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-19T00:00:00+00:00
[2024-03-01 11:29:56,067] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:29:56,073] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220919T000000, start_date=20240301T142955, end_date=20240301T142956
[2024-03-01 11:29:56,117] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:56,131] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
