[2024-03-01 11:19:45,960] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2024-03-01 11:19:45,964] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2024-03-01 11:19:45,964] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:45,964] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:45,964] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:45,978] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-21 00:00:00+00:00
[2024-03-01 11:19:45,981] {standard_task_runner.py:52} INFO - Started process 20166 to run task
[2024-03-01 11:19:45,983] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp6436hudd', '--error-file', '/tmp/tmpmrmhzd36']
[2024-03-01 11:19:45,984] {standard_task_runner.py:80} INFO - Job 25: Subtask cria_pasta
[2024-03-01 11:19:46,016] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:46,038] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:46,041] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221121T000000, start_date=20240301T141945, end_date=20240301T141946
[2024-03-01 11:19:46,053] {standard_task_runner.py:92} ERROR - Failed to execute job 25 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 20166)
[2024-03-01 11:19:46,077] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:46,101] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:22:52,187] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2024-03-01 11:22:52,193] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2024-03-01 11:22:52,193] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:52,193] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:52,193] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:52,210] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-21 00:00:00+00:00
[2024-03-01 11:22:52,213] {standard_task_runner.py:52} INFO - Started process 21877 to run task
[2024-03-01 11:22:52,216] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp757o8ymc', '--error-file', '/tmp/tmp9x0kst3o']
[2024-03-01 11:22:52,216] {standard_task_runner.py:80} INFO - Job 38: Subtask cria_pasta
[2024-03-01 11:22:52,246] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:52,291] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2024-03-01 11:22:52,292] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:22:52,292] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-11-28"']
[2024-03-01 11:22:52,298] {subprocess.py:85} INFO - Output:
[2024-03-01 11:22:52,300] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:22:52,319] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221121T000000, start_date=20240301T142252, end_date=20240301T142252
[2024-03-01 11:22:52,349] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:22:52,375] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:51,888] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2024-03-01 11:28:51,894] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2024-03-01 11:28:51,894] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:51,894] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:51,894] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:51,912] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-21 00:00:00+00:00
[2024-03-01 11:28:51,916] {standard_task_runner.py:52} INFO - Started process 23669 to run task
[2024-03-01 11:28:51,918] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpz643x4fq', '--error-file', '/tmp/tmpj25yd6km']
[2024-03-01 11:28:51,918] {standard_task_runner.py:80} INFO - Job 37: Subtask cria_pasta
[2024-03-01 11:28:51,992] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:52,036] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2024-03-01 11:28:52,036] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:28:52,037] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-11-28"']
[2024-03-01 11:28:52,043] {subprocess.py:85} INFO - Output:
[2024-03-01 11:28:52,044] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:28:52,064] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221121T000000, start_date=20240301T142851, end_date=20240301T142852
[2024-03-01 11:28:52,133] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:52,156] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:34,777] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2024-03-01 11:30:34,788] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [queued]>
[2024-03-01 11:30:34,789] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:34,789] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:34,789] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:34,847] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-21 00:00:00+00:00
[2024-03-01 11:30:34,853] {standard_task_runner.py:52} INFO - Started process 24444 to run task
[2024-03-01 11:30:34,857] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-21T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpdye1cpkp', '--error-file', '/tmp/tmpgbow094z']
[2024-03-01 11:30:34,857] {standard_task_runner.py:80} INFO - Job 38: Subtask cria_pasta
[2024-03-01 11:30:34,896] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-21T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:34,980] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-21T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-21T00:00:00+00:00
[2024-03-01 11:30:34,981] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:30:34,981] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-11-28"']
[2024-03-01 11:30:34,990] {subprocess.py:85} INFO - Output:
[2024-03-01 11:30:34,992] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:30:35,011] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221121T000000, start_date=20240301T143034, end_date=20240301T143035
[2024-03-01 11:30:35,031] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:35,056] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
