[2024-03-01 11:21:55,406] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:21:55,412] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:21:55,412] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:21:55,412] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:21:55,412] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:21:55,428] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-08-22 00:00:00+00:00
[2024-03-01 11:21:55,431] {standard_task_runner.py:52} INFO - Started process 21366 to run task
[2024-03-01 11:21:55,433] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp2yina4wc', '--error-file', '/tmp/tmp1n5db106']
[2024-03-01 11:21:55,434] {standard_task_runner.py:80} INFO - Job 14: Subtask extrai_dados
[2024-03-01 11:21:55,466] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:21:55,512] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2024-03-01 11:21:56,334] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 33, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-08-29'
[2024-03-01 11:21:56,340] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220822T000000, start_date=20240301T142155, end_date=20240301T142156
[2024-03-01 11:21:56,355] {standard_task_runner.py:92} ERROR - Failed to execute job 14 for task extrai_dados (Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-08-29'; 21366)
[2024-03-01 11:21:56,372] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:21:56,386] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:27:58,363] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:27:58,370] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:27:58,371] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:27:58,371] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:27:58,371] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:27:58,512] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-08-22 00:00:00+00:00
[2024-03-01 11:27:58,515] {standard_task_runner.py:52} INFO - Started process 23182 to run task
[2024-03-01 11:27:58,518] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpccqqborx', '--error-file', '/tmp/tmpsx581gkp']
[2024-03-01 11:27:58,519] {standard_task_runner.py:80} INFO - Job 14: Subtask extrai_dados
[2024-03-01 11:27:58,548] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:27:58,591] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2024-03-01 11:27:59,381] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:27:59,388] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220822T000000, start_date=20240301T142758, end_date=20240301T142759
[2024-03-01 11:27:59,418] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:27:59,431] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:38,029] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:29:38,035] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:29:38,035] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:38,035] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:38,035] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:38,050] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-08-22 00:00:00+00:00
[2024-03-01 11:29:38,053] {standard_task_runner.py:52} INFO - Started process 23937 to run task
[2024-03-01 11:29:38,055] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp7izo30yp', '--error-file', '/tmp/tmpmmvuqora']
[2024-03-01 11:29:38,055] {standard_task_runner.py:80} INFO - Job 14: Subtask extrai_dados
[2024-03-01 11:29:38,088] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-08-22T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:38,133] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2024-03-01 11:29:38,814] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:29:38,819] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220822T000000, start_date=20240301T142938, end_date=20240301T142938
[2024-03-01 11:29:38,874] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:38,890] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
