[2024-03-01 11:22:41,856] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:22:41,861] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:22:41,861] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:41,861] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:41,861] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:41,876] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-31 00:00:00+00:00
[2024-03-01 11:22:41,880] {standard_task_runner.py:52} INFO - Started process 21790 to run task
[2024-03-01 11:22:41,882] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-31T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpmlvejzgi', '--error-file', '/tmp/tmpiikardu1']
[2024-03-01 11:22:41,882] {standard_task_runner.py:80} INFO - Job 34: Subtask extrai_dados
[2024-03-01 11:22:41,913] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:41,955] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T00:00:00+00:00
[2024-03-01 11:22:42,662] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 33, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-11-07'
[2024-03-01 11:22:42,667] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221031T000000, start_date=20240301T142241, end_date=20240301T142242
[2024-03-01 11:22:42,681] {standard_task_runner.py:92} ERROR - Failed to execute job 34 for task extrai_dados (Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-11-07'; 21790)
[2024-03-01 11:22:42,702] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:22:42,714] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:43,081] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:28:43,088] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:28:43,088] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:43,088] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:43,088] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:43,104] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-31 00:00:00+00:00
[2024-03-01 11:28:43,108] {standard_task_runner.py:52} INFO - Started process 23595 to run task
[2024-03-01 11:28:43,110] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-31T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp8s033tpm', '--error-file', '/tmp/tmp7c32r679']
[2024-03-01 11:28:43,110] {standard_task_runner.py:80} INFO - Job 34: Subtask extrai_dados
[2024-03-01 11:28:43,142] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:43,185] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T00:00:00+00:00
[2024-03-01 11:28:43,991] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:28:43,997] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221031T000000, start_date=20240301T142843, end_date=20240301T142843
[2024-03-01 11:28:44,130] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:44,142] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:24,022] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:30:24,029] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [queued]>
[2024-03-01 11:30:24,029] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:24,029] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:24,029] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:24,046] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-31 00:00:00+00:00
[2024-03-01 11:30:24,049] {standard_task_runner.py:52} INFO - Started process 24357 to run task
[2024-03-01 11:30:24,052] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-31T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpvm1fcbtt', '--error-file', '/tmp/tmpdexrhi0o']
[2024-03-01 11:30:24,053] {standard_task_runner.py:80} INFO - Job 34: Subtask extrai_dados
[2024-03-01 11:30:24,084] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-31T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:24,128] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-31T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-31T00:00:00+00:00
[2024-03-01 11:30:24,806] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:30:24,811] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221031T000000, start_date=20240301T143024, end_date=20240301T143024
[2024-03-01 11:30:24,829] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:24,844] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
