[2024-03-01 11:22:34,858] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:22:34,865] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:22:34,865] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:34,865] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:34,865] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:34,880] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-24 00:00:00+00:00
[2024-03-01 11:22:34,883] {standard_task_runner.py:52} INFO - Started process 21722 to run task
[2024-03-01 11:22:34,886] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpkfxm20a0', '--error-file', '/tmp/tmpt679fym6']
[2024-03-01 11:22:34,886] {standard_task_runner.py:80} INFO - Job 31: Subtask extrai_dados
[2024-03-01 11:22:34,918] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-24T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:34,961] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-24T00:00:00+00:00
[2024-03-01 11:22:35,681] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 33, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-10-31'
[2024-03-01 11:22:35,686] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221024T000000, start_date=20240301T142234, end_date=20240301T142235
[2024-03-01 11:22:35,698] {standard_task_runner.py:92} ERROR - Failed to execute job 31 for task extrai_dados (Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-10-31'; 21722)
[2024-03-01 11:22:35,704] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:22:35,717] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:39,120] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:28:39,126] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:28:39,127] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:39,127] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:39,127] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:39,142] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-24 00:00:00+00:00
[2024-03-01 11:28:39,145] {standard_task_runner.py:52} INFO - Started process 23555 to run task
[2024-03-01 11:28:39,147] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpeoi6w6os', '--error-file', '/tmp/tmpy0pn8tkh']
[2024-03-01 11:28:39,148] {standard_task_runner.py:80} INFO - Job 32: Subtask extrai_dados
[2024-03-01 11:28:39,180] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-24T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:39,230] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-24T00:00:00+00:00
[2024-03-01 11:28:39,900] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:28:39,905] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221024T000000, start_date=20240301T142839, end_date=20240301T142839
[2024-03-01 11:28:39,926] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:39,940] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:20,026] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:30:20,031] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-24T00:00:00+00:00 [queued]>
[2024-03-01 11:30:20,032] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:20,032] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:20,032] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:20,049] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-10-24 00:00:00+00:00
[2024-03-01 11:30:20,053] {standard_task_runner.py:52} INFO - Started process 24317 to run task
[2024-03-01 11:30:20,055] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-10-24T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpnietg2o8', '--error-file', '/tmp/tmp2s4lwluu']
[2024-03-01 11:30:20,056] {standard_task_runner.py:80} INFO - Job 32: Subtask extrai_dados
[2024-03-01 11:30:20,088] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-10-24T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:20,134] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-10-24T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-24T00:00:00+00:00
[2024-03-01 11:30:20,793] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:30:20,799] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221024T000000, start_date=20240301T143020, end_date=20240301T143020
[2024-03-01 11:30:20,833] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:20,846] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
