[2024-03-01 11:19:17,238] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:19:17,244] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:19:17,244] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:17,244] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:17,244] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:17,260] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-22 00:00:00+00:00
[2024-03-01 11:19:17,262] {standard_task_runner.py:52} INFO - Started process 19888 to run task
[2024-03-01 11:19:17,264] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp90mlem02', '--error-file', '/tmp/tmpbsd0y2kv']
[2024-03-01 11:19:17,265] {standard_task_runner.py:80} INFO - Job 12: Subtask cria_pasta
[2024-03-01 11:19:17,297] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:17,319] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:17,323] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220822T000000, start_date=20240301T141917, end_date=20240301T141917
[2024-03-01 11:19:17,335] {standard_task_runner.py:92} ERROR - Failed to execute job 12 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 19888)
[2024-03-01 11:19:17,358] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:17,381] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:21:52,204] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:21:52,210] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:21:52,211] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:21:52,211] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:21:52,211] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:21:52,228] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-22 00:00:00+00:00
[2024-03-01 11:21:52,230] {standard_task_runner.py:52} INFO - Started process 21326 to run task
[2024-03-01 11:21:52,232] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpjw1aqpj2', '--error-file', '/tmp/tmpwo0ku5w5']
[2024-03-01 11:21:52,233] {standard_task_runner.py:80} INFO - Job 12: Subtask cria_pasta
[2024-03-01 11:21:52,265] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:21:52,308] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2024-03-01 11:21:52,309] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:21:52,309] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-08-29"']
[2024-03-01 11:21:52,315] {subprocess.py:85} INFO - Output:
[2024-03-01 11:21:52,317] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:21:52,334] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220822T000000, start_date=20240301T142152, end_date=20240301T142152
[2024-03-01 11:21:52,366] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:21:52,391] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:27:54,818] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:27:54,823] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:27:54,823] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:27:54,823] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:27:54,823] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:27:54,839] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-22 00:00:00+00:00
[2024-03-01 11:27:54,842] {standard_task_runner.py:52} INFO - Started process 23138 to run task
[2024-03-01 11:27:54,844] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpfyckjv82', '--error-file', '/tmp/tmpoebwk1gt']
[2024-03-01 11:27:54,845] {standard_task_runner.py:80} INFO - Job 12: Subtask cria_pasta
[2024-03-01 11:27:54,888] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:27:54,936] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2024-03-01 11:27:54,937] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:27:54,937] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-08-29"']
[2024-03-01 11:27:54,942] {subprocess.py:85} INFO - Output:
[2024-03-01 11:27:54,943] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:27:54,964] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220822T000000, start_date=20240301T142754, end_date=20240301T142754
[2024-03-01 11:27:55,018] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:27:55,040] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:34,731] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:29:34,738] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [queued]>
[2024-03-01 11:29:34,738] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:34,738] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:34,738] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:34,752] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-22 00:00:00+00:00
[2024-03-01 11:29:34,756] {standard_task_runner.py:52} INFO - Started process 23894 to run task
[2024-03-01 11:29:34,758] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-22T00:00:00+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp1c50yexi', '--error-file', '/tmp/tmpuckrr9nh']
[2024-03-01 11:29:34,758] {standard_task_runner.py:80} INFO - Job 12: Subtask cria_pasta
[2024-03-01 11:29:34,789] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-22T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:34,831] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-08-22T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-22T00:00:00+00:00
[2024-03-01 11:29:34,832] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:29:34,832] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-08-29"']
[2024-03-01 11:29:34,838] {subprocess.py:85} INFO - Output:
[2024-03-01 11:29:34,840] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:29:34,858] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220822T000000, start_date=20240301T142934, end_date=20240301T142934
[2024-03-01 11:29:34,891] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:34,915] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
