[2024-03-01 11:22:01,942] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:22:01,947] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:22:01,948] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:01,948] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:01,948] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:01,963] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-05 00:00:00+00:00
[2024-03-01 11:22:01,966] {standard_task_runner.py:52} INFO - Started process 21430 to run task
[2024-03-01 11:22:01,968] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpbk7iwept', '--error-file', '/tmp/tmpqopwj5pb']
[2024-03-01 11:22:01,969] {standard_task_runner.py:80} INFO - Job 17: Subtask extrai_dados
[2024-03-01 11:22:01,999] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-05T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:02,044] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2024-03-01 11:22:02,775] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 33, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-09-12'
[2024-03-01 11:22:02,780] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220905T000000, start_date=20240301T142201, end_date=20240301T142202
[2024-03-01 11:22:02,794] {standard_task_runner.py:92} ERROR - Failed to execute job 17 for task extrai_dados (Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-09-12'; 21430)
[2024-03-01 11:22:02,828] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:22:02,848] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:05,889] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:28:05,895] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:28:05,896] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:05,896] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:05,896] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:05,915] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-05 00:00:00+00:00
[2024-03-01 11:28:05,919] {standard_task_runner.py:52} INFO - Started process 23249 to run task
[2024-03-01 11:28:05,921] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpy6m3cadn', '--error-file', '/tmp/tmpbeqxcvsg']
[2024-03-01 11:28:05,921] {standard_task_runner.py:80} INFO - Job 17: Subtask extrai_dados
[2024-03-01 11:28:05,954] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-05T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:05,997] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2024-03-01 11:28:06,667] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:28:06,673] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220905T000000, start_date=20240301T142805, end_date=20240301T142806
[2024-03-01 11:28:06,699] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:06,712] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:44,679] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:29:44,686] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-05T00:00:00+00:00 [queued]>
[2024-03-01 11:29:44,686] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:44,686] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:44,686] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:44,702] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-05 00:00:00+00:00
[2024-03-01 11:29:44,706] {standard_task_runner.py:52} INFO - Started process 23999 to run task
[2024-03-01 11:29:44,708] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-05T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpjebp053w', '--error-file', '/tmp/tmpj_cx1sq3']
[2024-03-01 11:29:44,709] {standard_task_runner.py:80} INFO - Job 17: Subtask extrai_dados
[2024-03-01 11:29:44,741] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-05T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:44,785] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T00:00:00+00:00
[2024-03-01 11:29:45,439] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:29:45,444] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220905T000000, start_date=20240301T142944, end_date=20240301T142945
[2024-03-01 11:29:45,487] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:45,500] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
