[2024-03-01 11:19:18,953] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2024-03-01 11:19:18,960] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2024-03-01 11:19:18,960] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:18,960] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:18,960] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:18,976] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-29 00:00:00+00:00
[2024-03-01 11:19:18,979] {standard_task_runner.py:52} INFO - Started process 19908 to run task
[2024-03-01 11:19:18,981] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpqnkrbjyz', '--error-file', '/tmp/tmpmcpr4u6k']
[2024-03-01 11:19:18,982] {standard_task_runner.py:80} INFO - Job 13: Subtask cria_pasta
[2024-03-01 11:19:19,016] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:19,039] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:19,044] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220829T000000, start_date=20240301T141918, end_date=20240301T141919
[2024-03-01 11:19:19,057] {standard_task_runner.py:92} ERROR - Failed to execute job 13 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 19908)
[2024-03-01 11:19:19,075] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:19,097] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:21:53,877] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2024-03-01 11:21:53,883] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2024-03-01 11:21:53,883] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:21:53,883] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:21:53,883] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:21:53,899] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-29 00:00:00+00:00
[2024-03-01 11:21:53,902] {standard_task_runner.py:52} INFO - Started process 21347 to run task
[2024-03-01 11:21:53,904] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpepc6i538', '--error-file', '/tmp/tmp5g8kbxyl']
[2024-03-01 11:21:53,905] {standard_task_runner.py:80} INFO - Job 13: Subtask cria_pasta
[2024-03-01 11:21:53,933] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:21:53,975] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-29T00:00:00+00:00
[2024-03-01 11:21:53,976] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:21:53,977] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-05"']
[2024-03-01 11:21:53,982] {subprocess.py:85} INFO - Output:
[2024-03-01 11:21:53,984] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:21:54,001] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220829T000000, start_date=20240301T142153, end_date=20240301T142154
[2024-03-01 11:21:54,037] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:21:54,060] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:27:56,762] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2024-03-01 11:27:56,770] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2024-03-01 11:27:56,770] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:27:56,770] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:27:56,770] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:27:56,786] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-29 00:00:00+00:00
[2024-03-01 11:27:56,788] {standard_task_runner.py:52} INFO - Started process 23160 to run task
[2024-03-01 11:27:56,791] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpii24b8vt', '--error-file', '/tmp/tmp8_n3j19t']
[2024-03-01 11:27:56,791] {standard_task_runner.py:80} INFO - Job 13: Subtask cria_pasta
[2024-03-01 11:27:56,822] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:27:56,874] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-29T00:00:00+00:00
[2024-03-01 11:27:56,874] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:27:56,875] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-05"']
[2024-03-01 11:27:56,880] {subprocess.py:85} INFO - Output:
[2024-03-01 11:27:56,881] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:27:56,900] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220829T000000, start_date=20240301T142756, end_date=20240301T142756
[2024-03-01 11:27:56,924] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:27:56,946] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:36,470] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2024-03-01 11:29:36,476] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [queued]>
[2024-03-01 11:29:36,476] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:36,476] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:36,476] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:36,493] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-08-29 00:00:00+00:00
[2024-03-01 11:29:36,496] {standard_task_runner.py:52} INFO - Started process 23915 to run task
[2024-03-01 11:29:36,498] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-08-29T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpj3yilhbp', '--error-file', '/tmp/tmpvbyqjk6d']
[2024-03-01 11:29:36,498] {standard_task_runner.py:80} INFO - Job 13: Subtask cria_pasta
[2024-03-01 11:29:36,531] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-08-29T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:36,576] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-08-29T00:00:00+00:00
[2024-03-01 11:29:36,577] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:29:36,577] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-09-05"']
[2024-03-01 11:29:36,583] {subprocess.py:85} INFO - Output:
[2024-03-01 11:29:36,585] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:29:36,604] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220829T000000, start_date=20240301T142936, end_date=20240301T142936
[2024-03-01 11:29:36,632] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:36,655] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
