[2024-03-01 11:22:17,618] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:22:17,623] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:22:17,623] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:17,623] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:17,623] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:17,641] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-26 00:00:00+00:00
[2024-03-01 11:22:17,645] {standard_task_runner.py:52} INFO - Started process 21574 to run task
[2024-03-01 11:22:17,647] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp2yyudek3', '--error-file', '/tmp/tmp4qbdahy7']
[2024-03-01 11:22:17,648] {standard_task_runner.py:80} INFO - Job 24: Subtask extrai_dados
[2024-03-01 11:22:17,681] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-26T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:17,725] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2024-03-01 11:22:18,473] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 33, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-10-03'
[2024-03-01 11:22:18,479] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220926T000000, start_date=20240301T142217, end_date=20240301T142218
[2024-03-01 11:22:18,499] {standard_task_runner.py:92} ERROR - Failed to execute job 24 for task extrai_dados (Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-10-03'; 21574)
[2024-03-01 11:22:18,506] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:22:18,520] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:19,044] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:28:19,051] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:28:19,051] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:19,051] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:19,051] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:19,066] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-26 00:00:00+00:00
[2024-03-01 11:28:19,070] {standard_task_runner.py:52} INFO - Started process 23371 to run task
[2024-03-01 11:28:19,072] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpfvws3ye2', '--error-file', '/tmp/tmpsyzee3iu']
[2024-03-01 11:28:19,073] {standard_task_runner.py:80} INFO - Job 23: Subtask extrai_dados
[2024-03-01 11:28:19,104] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-26T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:19,149] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2024-03-01 11:28:19,808] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:28:19,814] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220926T000000, start_date=20240301T142819, end_date=20240301T142819
[2024-03-01 11:28:19,850] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:19,865] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:57,694] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:29:57,699] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:29:57,699] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:57,699] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:57,699] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:57,716] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-09-26 00:00:00+00:00
[2024-03-01 11:29:57,719] {standard_task_runner.py:52} INFO - Started process 24121 to run task
[2024-03-01 11:29:57,721] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp1945oq12', '--error-file', '/tmp/tmpaeb7k9m3']
[2024-03-01 11:29:57,721] {standard_task_runner.py:80} INFO - Job 23: Subtask extrai_dados
[2024-03-01 11:29:57,755] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-09-26T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:57,797] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2024-03-01 11:29:58,435] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:29:58,440] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20220926T000000, start_date=20240301T142957, end_date=20240301T142958
[2024-03-01 11:29:58,461] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:58,473] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
