[2024-03-01 11:19:28,119] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:19:28,124] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:19:28,124] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:28,124] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:28,124] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:28,140] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2024-03-01 11:19:28,143] {standard_task_runner.py:52} INFO - Started process 19996 to run task
[2024-03-01 11:19:28,145] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp5eu_qj45', '--error-file', '/tmp/tmpst4v8gby']
[2024-03-01 11:19:28,145] {standard_task_runner.py:80} INFO - Job 17: Subtask cria_pasta
[2024-03-01 11:19:28,178] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:28,203] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:28,209] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20240301T141928, end_date=20240301T141928
[2024-03-01 11:19:28,222] {standard_task_runner.py:92} ERROR - Failed to execute job 17 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 19996)
[2024-03-01 11:19:28,238] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:28,263] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:22:11,667] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:22:11,673] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:22:11,673] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:11,673] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:11,673] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:11,688] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2024-03-01 11:22:11,691] {standard_task_runner.py:52} INFO - Started process 21512 to run task
[2024-03-01 11:22:11,693] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpxn5iskix', '--error-file', '/tmp/tmpl1np25b5']
[2024-03-01 11:22:11,693] {standard_task_runner.py:80} INFO - Job 21: Subtask cria_pasta
[2024-03-01 11:22:11,723] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:11,770] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2024-03-01 11:22:11,770] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:22:11,771] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-03"']
[2024-03-01 11:22:11,776] {subprocess.py:85} INFO - Output:
[2024-03-01 11:22:11,778] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:22:11,797] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20240301T142211, end_date=20240301T142211
[2024-03-01 11:22:11,827] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:22:11,850] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:15,073] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:28:15,080] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:28:15,080] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:15,080] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:15,080] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:15,095] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2024-03-01 11:28:15,098] {standard_task_runner.py:52} INFO - Started process 23331 to run task
[2024-03-01 11:28:15,101] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp79r7t6px', '--error-file', '/tmp/tmpm1qtnrp0']
[2024-03-01 11:28:15,101] {standard_task_runner.py:80} INFO - Job 21: Subtask cria_pasta
[2024-03-01 11:28:15,133] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:15,176] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2024-03-01 11:28:15,177] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:28:15,178] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-03"']
[2024-03-01 11:28:15,183] {subprocess.py:85} INFO - Output:
[2024-03-01 11:28:15,185] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:28:15,205] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20240301T142815, end_date=20240301T142815
[2024-03-01 11:28:15,235] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:15,259] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:29:53,778] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:29:53,785] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [queued]>
[2024-03-01 11:29:53,785] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:53,785] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:29:53,785] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:29:53,800] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-09-26 00:00:00+00:00
[2024-03-01 11:29:53,804] {standard_task_runner.py:52} INFO - Started process 24081 to run task
[2024-03-01 11:29:53,806] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-09-26T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpc1l766h3', '--error-file', '/tmp/tmpn2vweiyx']
[2024-03-01 11:29:53,806] {standard_task_runner.py:80} INFO - Job 21: Subtask cria_pasta
[2024-03-01 11:29:53,837] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-09-26T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:29:53,880] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-09-26T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-26T00:00:00+00:00
[2024-03-01 11:29:53,881] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:29:53,881] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-03"']
[2024-03-01 11:29:53,887] {subprocess.py:85} INFO - Output:
[2024-03-01 11:29:53,889] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:29:53,907] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20220926T000000, start_date=20240301T142953, end_date=20240301T142953
[2024-03-01 11:29:53,940] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:29:53,965] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
