[2024-03-01 11:19:43,067] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:19:43,072] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:19:43,072] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:43,072] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:43,072] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:43,087] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2024-03-01 11:19:43,090] {standard_task_runner.py:52} INFO - Started process 20139 to run task
[2024-03-01 11:19:43,092] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpx8v8e6w6', '--error-file', '/tmp/tmpzw1hipsb']
[2024-03-01 11:19:43,093] {standard_task_runner.py:80} INFO - Job 24: Subtask cria_pasta
[2024-03-01 11:19:43,122] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:43,148] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:43,151] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20240301T141943, end_date=20240301T141943
[2024-03-01 11:19:43,163] {standard_task_runner.py:92} ERROR - Failed to execute job 24 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 20139)
[2024-03-01 11:19:43,186] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:43,212] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:22:44,390] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:22:44,397] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:22:44,397] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:44,397] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:44,397] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:44,416] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2024-03-01 11:22:44,420] {standard_task_runner.py:52} INFO - Started process 21810 to run task
[2024-03-01 11:22:44,422] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp_40t68bo', '--error-file', '/tmp/tmpgz7bccdo']
[2024-03-01 11:22:44,423] {standard_task_runner.py:80} INFO - Job 35: Subtask cria_pasta
[2024-03-01 11:22:44,459] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:44,505] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2024-03-01 11:22:44,506] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:22:44,507] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-11-21"']
[2024-03-01 11:22:44,512] {subprocess.py:85} INFO - Output:
[2024-03-01 11:22:44,514] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:22:44,534] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20240301T142244, end_date=20240301T142244
[2024-03-01 11:22:44,556] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:22:44,581] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:49,650] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:28:49,656] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:28:49,656] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:49,656] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:49,656] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:49,672] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2024-03-01 11:28:49,676] {standard_task_runner.py:52} INFO - Started process 23645 to run task
[2024-03-01 11:28:49,678] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpdzz7x5bd', '--error-file', '/tmp/tmp9kynyuc1']
[2024-03-01 11:28:49,679] {standard_task_runner.py:80} INFO - Job 36: Subtask cria_pasta
[2024-03-01 11:28:49,723] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:49,832] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2024-03-01 11:28:49,833] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:28:49,834] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-11-21"']
[2024-03-01 11:28:49,842] {subprocess.py:85} INFO - Output:
[2024-03-01 11:28:49,844] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:28:49,864] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20240301T142849, end_date=20240301T142849
[2024-03-01 11:28:49,932] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:49,958] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:26,656] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:30:26,661] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:30:26,662] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:26,662] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:26,662] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:26,676] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-11-14 00:00:00+00:00
[2024-03-01 11:30:26,679] {standard_task_runner.py:52} INFO - Started process 24377 to run task
[2024-03-01 11:30:26,681] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpv66pb10e', '--error-file', '/tmp/tmprn76b5qe']
[2024-03-01 11:30:26,682] {standard_task_runner.py:80} INFO - Job 35: Subtask cria_pasta
[2024-03-01 11:30:26,714] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-11-14T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:26,761] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2024-03-01 11:30:26,761] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:30:26,762] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-11-21"']
[2024-03-01 11:30:26,769] {subprocess.py:85} INFO - Output:
[2024-03-01 11:30:26,771] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:30:26,790] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221114T000000, start_date=20240301T143026, end_date=20240301T143026
[2024-03-01 11:30:26,855] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:26,878] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
