[2024-03-01 11:22:48,577] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:22:48,582] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:22:48,582] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:48,582] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:48,582] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:48,596] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-11-14 00:00:00+00:00
[2024-03-01 11:22:48,599] {standard_task_runner.py:52} INFO - Started process 21850 to run task
[2024-03-01 11:22:48,601] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp8rurlw0z', '--error-file', '/tmp/tmpire369eg']
[2024-03-01 11:22:48,602] {standard_task_runner.py:80} INFO - Job 37: Subtask extrai_dados
[2024-03-01 11:22:48,633] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-11-14T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:48,676] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2024-03-01 11:22:49,395] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/luan/Documents/airflowalura/dags/dados_climaticos.py", line 33, in extrai_dados
    dados.to_csv(file_path + 'dados_brutos.csv')
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/core/generic.py", line 3964, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-11-21'
[2024-03-01 11:22:49,400] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221114T000000, start_date=20240301T142248, end_date=20240301T142249
[2024-03-01 11:22:49,413] {standard_task_runner.py:92} ERROR - Failed to execute job 37 for task extrai_dados (Cannot save file into a non-existent directory: '/home/luan/Documents/datapipeline/semana=2022-11-21'; 21850)
[2024-03-01 11:22:49,419] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:22:49,431] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:53,515] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:28:53,523] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:28:53,523] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:53,523] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:53,523] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:53,539] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-11-14 00:00:00+00:00
[2024-03-01 11:28:53,542] {standard_task_runner.py:52} INFO - Started process 23683 to run task
[2024-03-01 11:28:53,545] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp14sipu4a', '--error-file', '/tmp/tmp4zw083qs']
[2024-03-01 11:28:53,545] {standard_task_runner.py:80} INFO - Job 38: Subtask extrai_dados
[2024-03-01 11:28:53,577] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-11-14T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:53,665] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2024-03-01 11:28:54,398] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:28:54,404] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221114T000000, start_date=20240301T142853, end_date=20240301T142854
[2024-03-01 11:28:54,443] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:54,457] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:30,869] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:30:30,876] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-11-14T00:00:00+00:00 [queued]>
[2024-03-01 11:30:30,876] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:30,876] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:30,876] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:30,939] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): extrai_dados> on 2022-11-14 00:00:00+00:00
[2024-03-01 11:30:30,943] {standard_task_runner.py:52} INFO - Started process 24417 to run task
[2024-03-01 11:30:30,945] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'extrai_dados', 'scheduled__2022-11-14T00:00:00+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpo1_y160b', '--error-file', '/tmp/tmp89iw2mus']
[2024-03-01 11:30:30,945] {standard_task_runner.py:80} INFO - Job 37: Subtask extrai_dados
[2024-03-01 11:30:30,977] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.extrai_dados scheduled__2022-11-14T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:31,065] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=extrai_dados
AIRFLOW_CTX_EXECUTION_DATE=2022-11-14T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-14T00:00:00+00:00
[2024-03-01 11:30:31,753] {python.py:173} INFO - Done. Returned value was: None
[2024-03-01 11:30:31,759] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=extrai_dados, execution_date=20221114T000000, start_date=20240301T143030, end_date=20240301T143031
[2024-03-01 11:30:31,803] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:31,814] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
