[2024-03-01 11:19:29,970] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2024-03-01 11:19:29,974] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2024-03-01 11:19:29,974] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:29,974] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:19:29,974] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:19:29,993] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2024-03-01 11:19:29,996] {standard_task_runner.py:52} INFO - Started process 20016 to run task
[2024-03-01 11:19:29,998] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmp5o1obnc5', '--error-file', '/tmp/tmpyv1vflk8']
[2024-03-01 11:19:29,998] {standard_task_runner.py:80} INFO - Job 18: Subtask cria_pasta
[2024-03-01 11:19:30,030] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:19:30,052] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1451, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1555, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 2212, in render_templates
    rendered_task = self.task.render_template_fields(context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1185, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/session.py", line 71, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 344, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/models/abstractoperator.py", line 391, in render_template
    return render_template_to_string(template, context)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 296, in render_template_to_string
    return render_template(template, context, native=False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/airflow/utils/helpers.py", line 291, in render_template
    return "".join(nodes)
  File "<template>", line 13, in root
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 391, in call
    if not __self.is_safe_callable(__obj):
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/sandbox.py", line 275, in is_safe_callable
    getattr(obj, "unsafe_callable", False) or getattr(obj, "alters_data", False)
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 910, in __getattr__
    return self._fail_with_undefined_error()
  File "/home/luan/Documents/airflowalura/venv/lib/python3.9/site-packages/jinja2/runtime.py", line 903, in _fail_with_undefined_error
    raise self._undefined_exception(self._undefined_message)
jinja2.exceptions.UndefinedError: 'pendulum.datetime.DateTime object' has no attribute 'srtftime'
[2024-03-01 11:19:30,056] {taskinstance.py:1395} INFO - Marking task as FAILED. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20240301T141929, end_date=20240301T141930
[2024-03-01 11:19:30,068] {standard_task_runner.py:92} ERROR - Failed to execute job 18 for task cria_pasta ('pendulum.datetime.DateTime object' has no attribute 'srtftime'; 20016)
[2024-03-01 11:19:30,092] {local_task_job.py:156} INFO - Task exited with return code 1
[2024-03-01 11:19:30,117] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:22:15,988] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2024-03-01 11:22:15,994] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2024-03-01 11:22:15,994] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:15,994] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:22:15,994] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:22:16,009] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2024-03-01 11:22:16,013] {standard_task_runner.py:52} INFO - Started process 21552 to run task
[2024-03-01 11:22:16,015] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpyd4d3bh7', '--error-file', '/tmp/tmpj_wewd2c']
[2024-03-01 11:22:16,015] {standard_task_runner.py:80} INFO - Job 23: Subtask cria_pasta
[2024-03-01 11:22:16,046] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:22:16,090] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-03T00:00:00+00:00
[2024-03-01 11:22:16,091] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:22:16,091] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-10"']
[2024-03-01 11:22:16,096] {subprocess.py:85} INFO - Output:
[2024-03-01 11:22:16,098] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:22:16,118] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20240301T142215, end_date=20240301T142216
[2024-03-01 11:22:16,148] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:22:16,170] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:28:22,571] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2024-03-01 11:28:22,576] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2024-03-01 11:28:22,576] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:22,576] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:28:22,576] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:28:22,591] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2024-03-01 11:28:22,594] {standard_task_runner.py:52} INFO - Started process 23398 to run task
[2024-03-01 11:28:22,597] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpgkedix7c', '--error-file', '/tmp/tmp_0631lrm']
[2024-03-01 11:28:22,598] {standard_task_runner.py:80} INFO - Job 24: Subtask cria_pasta
[2024-03-01 11:28:22,633] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:28:22,675] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-03T00:00:00+00:00
[2024-03-01 11:28:22,676] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:28:22,676] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-10"']
[2024-03-01 11:28:22,681] {subprocess.py:85} INFO - Output:
[2024-03-01 11:28:22,683] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:28:22,702] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20240301T142822, end_date=20240301T142822
[2024-03-01 11:28:22,730] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:28:22,752] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-03-01 11:30:01,220] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2024-03-01 11:30:01,226] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [queued]>
[2024-03-01 11:30:01,226] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:01,226] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2024-03-01 11:30:01,226] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-03-01 11:30:01,243] {taskinstance.py:1377} INFO - Executing <Task(BashOperator): cria_pasta> on 2022-10-03 00:00:00+00:00
[2024-03-01 11:30:01,246] {standard_task_runner.py:52} INFO - Started process 24148 to run task
[2024-03-01 11:30:01,248] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dados_climaticos', 'cria_pasta', 'scheduled__2022-10-03T00:00:00+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/dados_climaticos.py', '--cfg-path', '/tmp/tmpmh9np4hi', '--error-file', '/tmp/tmptln4mvfi']
[2024-03-01 11:30:01,249] {standard_task_runner.py:80} INFO - Job 24: Subtask cria_pasta
[2024-03-01 11:30:01,279] {task_command.py:370} INFO - Running <TaskInstance: dados_climaticos.cria_pasta scheduled__2022-10-03T00:00:00+00:00 [running]> on host BITL0401.
[2024-03-01 11:30:01,321] {taskinstance.py:1569} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dados_climaticos
AIRFLOW_CTX_TASK_ID=cria_pasta
AIRFLOW_CTX_EXECUTION_DATE=2022-10-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-03T00:00:00+00:00
[2024-03-01 11:30:01,322] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2024-03-01 11:30:01,322] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'mkdir -p "/home/luan/Documents/airflowalura/semana=2022-10-10"']
[2024-03-01 11:30:01,328] {subprocess.py:85} INFO - Output:
[2024-03-01 11:30:01,330] {subprocess.py:96} INFO - Command exited with return code 0
[2024-03-01 11:30:01,348] {taskinstance.py:1395} INFO - Marking task as SUCCESS. dag_id=dados_climaticos, task_id=cria_pasta, execution_date=20221003T000000, start_date=20240301T143001, end_date=20240301T143001
[2024-03-01 11:30:01,382] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-03-01 11:30:01,403] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
